FROM php:7.2-fpm

RUN rm /bin/sh && ln -s /bin/bash /bin/sh \
&& set -eux \
&& apt-get update --fix-missing \
&& apt-get install -y curl \
&& apt-get install -y build-essential libssl-dev zlib1g-dev libpng-dev libjpeg-dev libfreetype6-dev \
&& docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
&& docker-php-ext-install pdo_mysql opcache intl gd \
&& pecl install -o -f redis && docker-php-ext-enable redis \
&& rm -rf /tmp/* \
